# YAML is a superset of json. So by default it supports json.
# IMO yaml acts as a better config than json.
# Extra features: Comments, Anchors & Inheritance.
# Viper also supports YAML.
settings:
  server:
    host: 0.0.0.0:8066
  logger:
    info:  "/Users/hari.teja/logs/intent-score/info.log"
    error: "/Users/hari.teja/logs/intent-score/error.log"
  aerospike:
    connection-queue-size: 64
    limit-connections-queue-size: true
    hosts:
      - "192.168.0.6:3010"
  kafka:
    enable: false
    manthan:
      real_time_data:
        bootstrap-servers:
          - "192.168.0.6:9082"
        topics:
          - "manthan-real_time_data"
        auto-commit:  false
        heart-beat-interval:  3000
        session-timeout: 30000
        max-retries: 3
        interval-between-retries: 500
        metadata-refresh-interval:  36000
        partition-strategy:  "range"
        worker-count:  30
        log-bucket:  ""
        consumer-group-id:  "manthan-real_time_data"
        enable: true
