# YAML is a superset of json. So by default it supports json.
# IMO yaml acts as a better config than json.
# Extra features: Comments, Anchors & Inheritance.
# Viper also supports YAML.
settings:
  server:
    host: 0.0.0.0:8065
  logger:
    info:  "/logs/intent-score/info.log"
    error: "/logs/intent-score/error.log"
    key : ""
    key1: ""
    newrelic_key : "abcpqrxyz"

  aerospike:
    connection-queue-size: 64
    limit-connections-queue-size: true
    hosts:
      # - "aerospike:3000"
      - "aerospike:3001"
      - "aerospike:3002"
      - "aerospike:3003"
  kafka:
    enable: true
    manthan:
      real_time_data:
        bootstrap-servers:
          - "kafka:9092"
        topics:
          - "manthan-real_time_data"
        auto-commit:  false
        heart-beat-interval:  3000
        session-timeout: 30000
        max-retries: 3
        interval-between-retries: 500
        metadata-refresh-interval:  36000
        partition-strategy:  "range"
        worker-count:  30
        log-bucket:  ""
        consumer-group-id: "manthan-real_time_data"
        enable: true

